name: "\U0001F41E Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! **Before you start, make sure you have the latest versions of the packages you're using.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: steps to reproduce the behavior
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Device, OS, Browser, Version
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - annoyance
        - serious, but I can work around it
        - blocking an upgrade
        - blocking all usage of ICT Methods
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
