name: Production CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ⚙️
        working-directory: ./frontend
        run: npm ci
      - name: Linting 🛠
        working-directory: ./frontend
        run: npm run lint
      - name: Build frontend 👷
        working-directory: ./frontend
        run: npm run build --if-present
      - name: Testing frontend 🧪
        working-directory: ./frontend
        run: npm test --if-present
